name: Release

on: 
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Fetch Submodules
      shell: bash
      run: |
        git submodule init
        git submodule update

    - name: Check OS
      id: check_os
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
            echo "::set-output name=os::Linux"
            echo "::set-output name=ext::so"
        elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "::set-output name=os::Windows"
            echo "::set-output name=ext::dll"
        fi

    - name: Build (Windows)
      if: steps.check_os.outputs.os == 'Windows'
      shell: bash
      run: build.bat

    - name: Build (Linux)
      if: steps.check_os.outputs.os == 'Linux'
      shell: bash
      run: build.sh

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release ${{ github.ref }}
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      id: upload_release_assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/angelscript-module.${{ steps.check_os.outputs.ext }}
        asset_name: angelscript-module.${{ steps.check_os.outputs.ext }}
