name: Release

on: 
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: windows-latest
    outputs:
      url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release ${{ github.ref }}
        draft: false
        prerelease: false

  build:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            OS_TYPE: Windows
            EXT: dll
          - os: ubuntu-18.04
            OS_TYPE: Linux
            EXT: so

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true

    - name: Build server (Windows)
      if: matrix.OS_TYPE == 'Windows'
      shell: bash
      run: |
        cd .\\tools
        .\\build-server.bat

    #- name: Build client (Windows)
    #  if: matrix.OS_TYPE == 'Windows'
    #  shell: bash
    #  run: |
    #    rm -rf ./build
    #    cd .\\tools
    #    .\\build-client.bat

    - name: Build (Linux)
      if: matrix.OS_TYPE == 'Linux'
      shell: bash
      run: |
        chmod 777 ./tools/build.sh
        cd ./tools
        ./build.sh

    - name: Upload Release Server Assets
      id: upload_release_assets_server
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.url }}
        asset_path: ./dist/server/angelscript-module.${{ matrix.EXT }}
        asset_name: angelscript-module.${{ matrix.EXT }}
        asset_content_type: application/octet-stream

    #- name: Upload Release Client Assets
    #  if: matrix.OS_TYPE == 'Windows'
    #  id: upload_release_assets_client
    #  uses: actions/upload-release-asset@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    ##    upload_url: ${{ steps.get_release.outputs.upload_url }}
    #    asset_path: ./dist/client/angelscript-client-module.${{ matrix.EXT }}
    #    asset_name: angelscript-client-module.${{ matrix.EXT }}
    #    asset_content_type: application/octet-stream
